
CREATE TABLE BVL_COMPANY
(
    STOCK CHAR(10),
    CATEGORY VARCHAR(20)
)


CREATE TABLE BVL_STOCK_PRICE
(
    STOCK CHAR(10),
    DATE_PRICE DATE,
    YEAR CHAR(4),
    MONTH INT,
    PRICE FLOAT    
)


CREATE TABLE BVL_INCOME_STATEMENT
(
    STOCK CHAR(10),
    ITEM VARCHAR(50),
    YEAR CHAR(4),
    QUARTER CHAR(1),
    VALUE FLOAT,
    CURRENCY CHAR(3)
)


CREATE TABLE BVL_BALANCE_SHEET
(
    STOCK CHAR(10),
    ITEM VARCHAR(50),
    YEAR CHAR(4),
    QUARTER CHAR(1),
    VALUE FLOAT,
    CURRENCY CHAR(3)
)


CREATE TABLE BVL_CASH_FLOW
(
    STOCK CHAR(10),
    ITEM VARCHAR(50),
    YEAR CHAR(4),
    QUARTER CHAR(1),
    VALUE FLOAT,
    CURRENCY CHAR(3)
)


CREATE VIEW V_INCOME_STATISTICS
AS

    SELECT 
        A.STOCK, 
        A.YEAR,
        A.QUARTER,
        A.VALUE AS SALES,
        GI.VALUE AS GROSS_INCOME,
        NI.VALUE AS NET_INCOME,
        ifnull(EB.VALUE, 0) AS EBITDA,
        EPB.VALUE AS EPS_BASIC,
        EPD.VALUE AS EPS_DILUTED,
        SHA.VALUE AS TOTAL_BASIC_SHARES,
        A.CURRENCY
    FROM BVL_INCOME_STATEMENT AS A

        LEFT JOIN BVL_STOCK_PRICE AS PRI
        ON PRI.STOCK=A.STOCK
        AND PRI.YEAR=A.YEAR
    
        LEFT JOIN BVL_INCOME_STATEMENT AS GI
        ON GI.STOCK=A.STOCK
        AND GI.ITEM='Gross Income'
        AND GI.YEAR=A.YEAR
        AND GI.QUARTER=A.QUARTER
        AND GI.CURRENCY=A.CURRENCY
    
        LEFT JOIN BVL_INCOME_STATEMENT AS EB
        ON EB.STOCK=A.STOCK
        AND EB.ITEM='EBITDA'
        AND EB.YEAR=A.YEAR
        AND EB.QUARTER=A.QUARTER
        AND EB.CURRENCY=A.CURRENCY
    
        LEFT JOIN BVL_INCOME_STATEMENT AS NI
        ON NI.STOCK=A.STOCK
        AND NI.ITEM='Net Income'
        AND NI.YEAR=A.YEAR
        AND NI.QUARTER=A.QUARTER
        AND NI.CURRENCY=A.CURRENCY

        LEFT JOIN BVL_INCOME_STATEMENT AS EPB
        ON EPB.STOCK=A.STOCK
        AND EPB.ITEM='EPS (Basic)'
        AND EPB.YEAR=A.YEAR
        AND EPB.QUARTER=A.QUARTER
        AND EPB.CURRENCY=A.CURRENCY

        LEFT JOIN BVL_INCOME_STATEMENT AS EPD
        ON EPD.STOCK=A.STOCK
        AND EPD.ITEM='EPS (Diluted)'
        AND EPD.YEAR=A.YEAR
        AND EPD.QUARTER=A.QUARTER
        AND EPD.CURRENCY=A.CURRENCY
        
        LEFT JOIN BVL_INCOME_STATEMENT AS SHA
        ON SHA.STOCK=A.STOCK
        AND SHA.ITEM='Basic Shares Outstanding'
        AND SHA.YEAR=A.YEAR
        AND SHA.QUARTER=A.QUARTER
        AND SHA.CURRENCY=A.CURRENCY
        
    WHERE A.ITEM='Sales/Revenue';

    
CREATE VIEW V_BALANCE_SHEET
AS

    SELECT 
        C.STOCK,
        C.YEAR,
        C.QUARTER,
        C.CURRENCY,
        C.VALUE AS TOTAL_ASSETS,
        ifnull(TCA.VALUE, 0) AS TOTAL_CURRENT_ASSETS,
        ifnull(TCL.VALUE, 0) AS TOTAL_CURRENT_LIABILITIES,
        ifnull(TL.VALUE, 0) AS TOTAL_LIABILITIES,
        ifnull(CE.VALUE, 0) AS COMMON_EQUITY,
        ifnull(RE.VALUE, 0) AS RETAINED_EARNINGS,
        ifnull(TEQ.VALUE, 0) AS TOTAL_EQUITY,
        ifnull(NI.VALUE, 0) AS NET_INCOME
    FROM BVL_BALANCE_SHEET AS C
    
        LEFT JOIN BVL_BALANCE_SHEET AS TCA
        ON TCA.STOCK=C.STOCK
        AND TCA.YEAR=C.YEAR
        AND TCA.QUARTER=C.QUARTER
        AND TCA.ITEM='Total Current Assets'
        AND TCA.CURRENCY=C.CURRENCY
        
        LEFT JOIN BVL_BALANCE_SHEET AS TCL
        ON TCL.STOCK=C.STOCK
        AND TCL.YEAR=C.YEAR
        AND TCL.QUARTER=C.QUARTER
        AND TCL.ITEM='Total Current Liabilities'
        AND TCL.CURRENCY=C.CURRENCY
    
        LEFT JOIN BVL_BALANCE_SHEET AS TL
        ON TL.STOCK=C.STOCK
        AND TL.YEAR=C.YEAR
        AND TL.QUARTER=C.QUARTER
        AND TL.ITEM='Total Liabilities'
        AND TL.CURRENCY=C.CURRENCY
        
        LEFT JOIN BVL_BALANCE_SHEET AS CE
        ON CE.STOCK=C.STOCK
        AND CE.YEAR=C.YEAR
        AND CE.QUARTER=C.QUARTER
        AND CE.ITEM='Common Equity (Total)'
        AND CE.CURRENCY=C.CURRENCY
        
        LEFT JOIN BVL_BALANCE_SHEET AS RE
        ON RE.STOCK=C.STOCK
        AND RE.YEAR=C.YEAR
        AND RE.QUARTER=C.QUARTER
        AND RE.ITEM='Retained Earnings'
        AND RE.CURRENCY=C.CURRENCY
        
        LEFT JOIN BVL_BALANCE_SHEET AS TEQ
        ON TEQ.STOCK=C.STOCK
        AND TEQ.YEAR=C.YEAR
        AND TEQ.QUARTER=C.QUARTER
        AND TEQ.ITEM='Total Equity'
        AND TEQ.CURRENCY=C.CURRENCY

        LEFT JOIN BVL_INCOME_STATEMENT AS NI
        ON NI.STOCK=C.STOCK
        AND NI.YEAR=C.YEAR
        AND NI.QUARTER=C.QUARTER
        AND NI.ITEM='Net Income'
        AND NI.CURRENCY=C.CURRENCY
    
    WHERE C.ITEM='Total Assets';


CREATE VIEW V_CASH_FLOW
AS

    SELECT
        C.STOCK,
        C.YEAR,
        C.QUARTER,
        C.CURRENCY,
        C.VALUE AS NET_OPERATING_CASH_FLOW,
        FIN.VALUE AS NET_FINANCING_CASH_FLOW,
        INV.VALUE AS NET_INVESTING_CASH_FLOW,
        FREE.VALUE AS FREE_CASH_FLOW,
        NCH.VALUE AS NET_CHANGE_IN_CASH
    FROM BVL_CASH_FLOW AS C
    
        LEFT JOIN BVL_CASH_FLOW AS FIN
        ON FIN.STOCK=C.STOCK
        AND FIN.YEAR=C.YEAR
        AND FIN.QUARTER=C.QUARTER
        AND FIN.ITEM='Net Financing Cash Flow'
        AND FIN.CURRENCY=C.CURRENCY
    
        LEFT JOIN BVL_CASH_FLOW AS INV
        ON INV.STOCK=C.STOCK
        AND INV.YEAR=C.YEAR
        AND INV.QUARTER=C.QUARTER
        AND INV.ITEM='Net Investing Cash Flow'
        AND INV.CURRENCY=C.CURRENCY
    
        LEFT JOIN BVL_CASH_FLOW AS FREE
        ON FREE.STOCK=C.STOCK
        AND FREE.YEAR=C.YEAR
        AND FREE.QUARTER=C.QUARTER
        AND FREE.ITEM='Free Cash Flow'
        AND FREE.CURRENCY=C.CURRENCY
    
        LEFT JOIN BVL_CASH_FLOW AS NCH
        ON NCH.STOCK=C.STOCK
        AND NCH.YEAR=C.YEAR
        AND NCH.QUARTER=C.QUARTER
        AND NCH.ITEM='Net Change in Cash'
        AND NCH.CURRENCY=C.CURRENCY	
    
    WHERE C.ITEM='Net Operating Cash Flow';


CREATE VIEW V_STOCK_PRICE
AS 

    SELECT 
        P.STOCK,
        P.YEAR,
        P.MONTH,
        P.PRICE
    FROM BVL_STOCK_PRICE AS P
    
        INNER JOIN (SELECT 
                    A.STOCK,
                    A.YEAR,
                    MAX(A.MONTH) AS MONTH
                FROM BVL_STOCK_PRICE AS A
                GROUP BY A.STOCK, A.YEAR) AS M
        ON M.STOCK=P.STOCK
        AND M.YEAR=P.YEAR
        AND M.MONTH=P.MONTH;

        
INSERT INTO BVL_COMPANY 
VALUES ('CASAGRC1', 'AGRO'),
('CARTAVC1', 'AGRO'),
('LAREDOC1', 'AGRO'),
('CPACASC1', 'INDUSTRIAL'),
('UNACEMC1', 'INDUSTRIAL'),
('FERREYC1', 'INDUSTRIAL'),
('SIDERC1', 'INDUSTRIAL'),
('CORAREI1', 'INDUSTRIAL'),
('PODERC1', 'MINING'),
('CVERDEC1', 'MINING'),
('SCCO', 'MINING'),
('MINSURI1', 'MINING'),
('ALICORC1', 'MASSIVE CONSUMPTION'),
('BACKUSI1', 'MASSIVE CONSUMPTION'),
('INRETC1', 'MASSIVE CONSUMPTION'),
('LUSURC1', 'UTILITIES'),
('ENGEPEC1', 'UTILITIES'),
('ENDISPC1', 'UTILITIES'),
('HIDRA2C1', 'UTILITIES'),
('ENGIEC1', 'UTILITIES'),
('BBVAC1', 'FINANCE'),
('CREDITC1', 'FINANCE'),
('SCOTIAC1', 'FINANCE'),
('INTERBC1', 'FINANCE');




SELECT * FROM BVL_INCOME_STATEMENT
WHERE ITEM NOT IN ('COGS excluding D&A', 'Depreciation', 'Amortization of Intangibles',
    'SG&A Expense', 'Other SG&A', 'Other Operating Expense', 
    'EBIT', 'Unusual Expense', 'Non Operating Income/Expense',
    'Non-Operating Interest Income', 'Gross Interest Expense', 'Income Tax - Current Domestic',
    'Income Tax - Deferred Domestic', 'Equity in Affiliates', 'Discontinued Operations',
    'Net Income After Extraordinaries', 'Net Income Available to Common', 'Pretax Income',
    'Extraordinaries & Discontinued Operations')
//where LOWER(STOCK) IN ('minsuri1', 'scco', 'engiec1', 'inretc1', 'bap', 'ifs', 'scotiac1', 'bbvac1');


select stock, count(*) as total 
from BVL_INCOME_STATEMENT
group by stock
order by stock


SELECT * FROM V_INCOME_STATISTICS
ORDER BY STOCK, YEAR, QUARTER;


//delete FROM BVL_INCOME_STATEMENT
//WHERE STOCK IN ('BBVAC1', 'CREDITC1', 'SCOTIAC1', 'INTERBC1')


    

SELECT * FROM BVL_BALANCE_SHEET
where stock='PODERC1'


SELECT 
    STOCK, COUNT(*)
FROM BVL_BALANCE_SHEET
GROUP BY STOCK
order by STOCK


SELECT * FROM V_BALANCE_SHEET
ORDER BY STOCK, YEAR, QUARTER


//DELETE FROM BVL_BALANCE_SHEET
//WHERE STOCK=''

//delete from BVL_CASH_FLOW
//WHERE STOCK IN ('CASAGRC1', 'CARTAVC1', 'LAREDOC1')


SELECT * FROM BVL_CASH_FLOW

SELECT 
    STOCK, COUNT(*)
FROM bvl_cash_flow
GROUP BY STOCK


SELECT * FROM V_CASH_FLOW
WHERE STOCK='CASAGRC1'
AND QUARTER IN (1,2,3,4)
ORDER BY STOCK, YEAR, QUARTER


//DELETE FROM BVL_CASH_FLOW


SELECT * FROM V_STOCK_PRICE    
ORDER BY STOCK, YEAR


SELECT *
FROM V_STOCK_PRICE 
